version: '3'
services:
  backend:
    build: .
    command: >
      sh -c "npm run deploy &&
             npm  run start"
    env_file: ${ENV_FILE}
    ports: 
      - 4000:4000
    depends_on:
      - prisma
    restart: always
  